server:
  port: 9528

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true



spring:
  application:
    name: microservicecloud-zuul-gateway




info:
  app.name: csii-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: micro-server-dept
    mydept.path: /mydept/**
  ignored-services: micro-server-dept
